# Generated by Django 3.1.3 on 2021-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210203_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_photo',
            field=models.ImageField(upload_to='blog/media/image/news'),
        ),
    ]
