# Generated by Django 3.1.3 on 2021-02-07 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210203_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/news/image/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
